// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// Main_Simulate
Rcpp::List Main_Simulate(arma::vec theta, Rcpp::List SetupVars, double T_record, bool CellTracking);
RcppExport SEXP _FUCCIGillespie_Main_Simulate(SEXP thetaSEXP, SEXP SetupVarsSEXP, SEXP T_recordSEXP, SEXP CellTrackingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type SetupVars(SetupVarsSEXP);
    Rcpp::traits::input_parameter< double >::type T_record(T_recordSEXP);
    Rcpp::traits::input_parameter< bool >::type CellTracking(CellTrackingSEXP);
    rcpp_result_gen = Rcpp::wrap(Main_Simulate(theta, SetupVars, T_record, CellTracking));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_FUCCIGillespie_Main_Simulate", (DL_FUNC) &_FUCCIGillespie_Main_Simulate, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_FUCCIGillespie(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
