# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Main_Simulate <- function(theta, SetupVars, T_record, CellTracking) {
    .Call(`_FUCCIGillespie_Main_Simulate`, theta, SetupVars, T_record, CellTracking)
}

